# Generated by Django 3.2.4 on 2021-06-05 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_champion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('staring', models.CharField(blank=True, max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('rating', models.EmailField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bldgroom',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
    ]
