# Generated by Django 3.2.4 on 2021-06-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_champion', '0002_auto_20210604_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=100),
        ),
    ]
